# openai_api_key: "YOUR OPENAI KEY"
openai_api_key: "YOUR SECRET KEY"

openai_key: "YOUR OPENAI API KEY"
tmdb_access_token: "YOUR TMDB ACCESS TOKEN"
spotipy_client_id: "YOUR SPOTIFY APPLICATION CLIENT ID"
spotipy_client_secret: "YOUR SPOTIFY APPLCIATION CLIENT SECRET"
spotipy_redirect_uri: "URL TO YOUR APPLICATION"
YOUR_SCENARIO_KEY: "YOUR SCENARIO KEY HERE"
YOUR_SCENARIO_SECRET_IF_ANY: "YOUR SCENARIO SECRET HERE"

#spotipy_client_id: "884afca3fc194cd7a00a01210f85d826"
#spotipy_client_secret: "f0dcc4a6d3d449c5a22cd8b9e66e4d2b"
#spotipy_redirect_uri: "http://localhost/"

NOTION_KEY: "YOUR SECRET KEY"
NOTION_PAGE_ID: "ed0eab8fa04541f58a4024ecb35fde8a"
NOTION_VERSION: "2022-02-22"

UPCLICK_KEY: "YOUR SECRET KEY"

discord_client_id: "1163748696425500745"
discord_client_secret: "YOUR SECRET KEY"
discord_redirect_uri: "http://localhost/"

google_token: "YOUR SECRET KEY"
# trello_key: "e0163c45ef216569c30b4ad902f9c524"
# trello_token: "YOUR SECRET KEY"
